services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports:
      - "8080:80"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'qwerty12345'
        puma['worker_processes'] = 0
        external_url 'http://localhost:8000'
        nginx['listen_port'] = 8000
        sidekiq['max_concurrency'] = 5
      GITLAB_ROOT_EMAIL: "penanava1@gmail.com"
    networks:
      - devsecops-net
    # restart: unless-stopped
    # mem_limit: 2g
    # cpus: 2

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
