services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf.toml:/etc/gitlab-runner/config.toml
    networks:
      - devsecops-net
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.5
