export const dConfig = {
	timerDuration: 55,
	setTime: '04:00',
	timeAddSubStep: '00:05',
	shuffleKey: 'KeyR',
	toggleTimer: 'KeyW',
	pauseKey: 'Space',
	theme: 'green',
	shuffleAnimation: "Replace",
	hideAllUI: false,
	extraButtonsOn: true,
	extraButtonsPauseOn: true,
	panelAutoPause: true,
	panelAutoOpen: true,
	menuAutoPause: true,
	timerBlackOut: true,
	timerEndSound: true,
	afterSound: true,
	introGuide: true,
	audioTimerEnd: null,
	playerBackground: true,
	usingBackroundImage: false,
	backgroundImage: null
};
